### ISSUE TITLE
New Member Registration Error

### ISSUE THREAD

**Issue by pd2xsl** [DevBetterCom/DevBetterWeb#1002]
Hi guys.

Great to be here. I signed up last night but got the following after registering.

I can log in etc but not sure if I missed any instructions/welcome email or anything?

![devbetter issue](https://user-images.githubusercontent.com/112548829/212565302-7e627405-6af4-4f34-b258-c1dc6967bc55.png)

**Comment by ardalis** [comment]
I'll get you set up

**Comment by ardalis** [comment]
I think this is fixed.
