### ISSUE TITLE
Discord integration is down

### ISSUE THREAD

**Issue by snowfrogdev** [DevBetterCom/DevBetterWeb#1031]
It looks like we're no longer getting DevBetter related messages in our Discord server.

The last notification seems to be from Dec 23, 2022.
![image](https://user-images.githubusercontent.com/22530235/223400058-af586dba-68e7-41f1-b83c-801da18b61a9.png)
![image](https://user-images.githubusercontent.com/22530235/223400337-af2dcee5-658e-4752-a2b6-45b551e9c2bf.png)

**Comment by ardalis** [comment]
I got an admin-only one on 9 Jan 2023. They stopped then.
