### ISSUE TITLE
Admin - Member - Subscription Details

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#105]
There is already a User Admin page here:
https://devbetter.com/Admin/User?userId=b402b31c-a417-41ec-9a53-bf7116862c01

This is where the functionality should be placed, since between subscriptions users won't appear on the Member Admin page.

It might look something like this (use the same fonts and button styles as are already there):
![image](https://user-images.githubusercontent.com/782127/87338461-3a37b000-c513-11ea-9ae7-31f7405678f5.png)

Requirements:

- Add Subscription opens a box where user can enter a Start Date (required) and optional End Date. Save or Cancel.
- Edit User page lists all Subcriptions, ordered by Start Date
- Any Subscription with a null End Date should say "Present" as shown in the mockup
- Subscriptions cannot overlap - detect before saving and have user correct the data.
- Subscriptions can be removed - they are simply deleted from the database
- Display a count of the total number of days the user has been a subscriber.

**Comment by samuelwine** [comment]
I set up the database (using migrations) with a Subscription table that has a foreign key reference to MembersID. Tonight I'm thinking that that's wrong as subscriptions really belong to Users (as between subscriptions they are still a user but not a member). If that's right, I'm not sure then how to proceed as Users are in the Identity dbContext so how would I link the subscription to the user with EF?
I hope this makes sense!

**Comment by ardalis** [comment]
I'll have a look but I think your initial thought was right. I don't really want Users to have many domain dependencies. I want to keep "user" as a separate Authentication concept. The domain thing is a Member. A Member might actually be a "potential" Member or an "expired" Member but I would still use Member as the concept within the domain, not user. Does that help?

**Comment by samuelwine** [comment]
Yes definitely, thanks for this.

**Comment by samuelwine** [comment]
Do we need to validate that the subscription expiry data is not before the start date?
If yes, where is the right place to implement this? - i would have thought that on the entity itself would be the right place (in keeping with ddd principles), but then we won't get client-side validation as we are using a DTO.

**Comment by ardalis** [comment]
We should do it in the domain model. There are a few ways to do this:

- Use a custom value type that must be in the right format. A `DateTimeRange` is one approach. I cover this in my DDD Fundamentals course on Pluralsight, but it's a simple 2-property value type that takes in its values in its constructor and ensures right there that the end-date follows the start date, otherwise it throws an exception.
- Use a separate validator. You can use FluentValidation library to do this easily, and the same validator can be used in the UI parts of the app.

For something this simple it wouldn't bother me at all if the client side had to implement the same check with some code duplication. For client-side (javascript) checks with a .NET back end this duplication is usually there anyway.

**Comment by samuelwine** [comment]
Thanks for this!
Does there need to be a Edit Subscription button e.g. to be able to set an EndDate for a subscription?

**Comment by ardalis** [comment]
Yes, that makes sense.

**Comment by samuelwine** [comment]
Almost there now!
There is just one more requirement - to ensure subscriptions don't overlap.
Just confirming that it should be possible to enter a subscription that starts and finishes before a subscription that is already in the database (e.g, a subscription that was overlooked and not entered in the system and is discovered at a later date)

**Comment by ardalis** [comment]
Yes, we should allow creating subscriptions so they precede existing ones, to cover the scenario you describe. Thanks!

**Comment by ardalis** [comment]
I think this is done. If there still needs to be a non-overlapping feature added we can open a separate issue/bug for that.
