### ISSUE TITLE
Add a Map with Pins for every Member

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#107]
Should be a private members-only feature.

**Comment by ardalis** [comment]
Maybe just use city or zip code for world map pins.

**Comment by ardalis** [comment]
This may be useful to get started: https://www.aspsnippets.com/Articles/ASPNet-Core-Implement-Google-Maps-from-Database-in-Net-Core.aspx

**Comment by samuelwine** [comment]
![map-marker](https://user-images.githubusercontent.com/15095510/100027401-a214d600-2de4-11eb-83ff-0a9bb99d1f6e.png)
If you need it in a different format, let me know

**Comment by ardalis** [comment]
How is this progressing? Need any help?

**Comment by samuelwine** [comment]
Apologies this has been a bit neglected!
How is the address stored in the DB - is it comma seperated within dbo.Members address field?
Just thinking how to extract the city from there

**Comment by samuelwine** [comment]
Also whereabout on the site is this map to go?

**Comment by ardalis** [comment]
For now how about a link at the top of the Member list, here:
https://devbetter.com/User

I think I'll need a better signed-in navigation experience soon as we keep adding more features.

**Comment by samuelwine** [comment]
just making sure i got this right - do you mean add a link to the User page that will display the map in a modal window or a different page?

**Comment by ardalis** [comment]
No modal; different page. Maybe /User/Map for example.

The map icons on the member list also should probably point to the map once it's present and working.

**Comment by samuelwine** [comment]
ok, got that, thanks.
one more question - how is the address stored in the DB - is it comma seperated within dbo.Members address field?
Just thinking how to extract the city from there

**Comment by samuelwine** [comment]
also - I was wondering whether you might want to display the map on the home page, as it looks quite impressive to a prospective member that devBetter is an international org?

**Comment by ardalis** [comment]
Yes.

Good question on how to extract city. I recommend using an API. We don't need to do it very often and we can store the city separately in the profile if that's easier. For now just do it on the Map page for each address and then cache it for a long time so we don't hammer any external API with requests. Make sure to do it server-side too so we aren't leaking real address info in the client.

https://stackoverflow.com/a/16887/13729

**Comment by ardalis** [comment]
Possibly - for now keep it authorize-only. I can always use a still image for marketing if desired.

**Comment by samuelwine** [comment]
I got myself into some trouble publishing my GoogleMapsAPI key on Github
![image](https://user-images.githubusercontent.com/15095510/103136368-a704c800-46b7-11eb-848b-548bbb54b170.png)
What is the right way to store it?
Thanks

**Comment by ardalis** [comment]
Just catching up on email now, sorry for not replying sooner. You don't want to check in API keys. Instead, keep them locally in an appsettings.Development.json file and add that file to your .gitignore so it doesn't go into source. In the base appsettings.json file, you can add the key with a blank value (or "Your Google API key here").

In production, these settings will be added as environment variables, so they won't ever be in the file system there, either. They get added in the Azure portal by an administrator.

**Comment by samuelwine** [comment]
Thanks for this.
How though is the API key kept secret when its in production, isn't it visible in browser debugger?

**Comment by ardalis** [comment]
I haven't looked into the details but apparently you can add restrictions to keys so they don't work from anywhere, such as HTTP Referer values:
https://cloud.google.com/blog/products/maps-platform/google-maps-platform-best-practices-restricting-api-keys

**Comment by ardalis** [comment]
I would set up a production key as part of deployment and I would restrict it to only work on *.devbetter.com for instance.

**Comment by samuelwine** [comment]
I get that - but then is it not really such an issue to check the API key into source code if its anyway restricted to that site? Obviously I understand its not good practice, but just wondering if i'm missing something? 
Thanks

**Comment by samuelwine** [comment]
Can you advise me on this?
Thank you

**Comment by ardalis** [comment]
Yes, you're correct, it shouldn't be a huge deal. But it's still a leak and could be used for instance by someone on localhost with a hosts file saying their local machine was actually devbetter.com, and then from there they could use our key to do whatever they wanted. So, best not to check it in, and if you do, best to reset it.

**Comment by samuelwine** [comment]
@ardalis Is this complete - can it be closed?

**Comment by snowfrogdev** [comment]
> @ardalis Is this complete - can it be closed?

bump 😊

**Comment by ardalis** [comment]
Sure
