### ISSUE TITLE
Add YouTube to User page

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#111]
This page should include the YouTube link with an icon like the others. It should be a Blue Link if it's set and a Black icon otherwise.

![image](https://user-images.githubusercontent.com/782127/90289472-f3a6df80-de49-11ea-9c09-3c1397f39cca.png)

The link should likewise appear on the /User/Details page, between Twitter and Other:
![image](https://user-images.githubusercontent.com/782127/90289536-146f3500-de4a-11ea-8be6-30a76892390a.png)

**Comment by ardalis** [comment]
Also make the links all default to subscribe links:

?sub_confirmation=1

See: 
https://seattlewebsearch.com/2017/05/make-youtube-url-auto-subscribes-channel/

**Comment by ardalis** [comment]
Example:
https://youtube.com/ardalis?sub_confirmation=1

Opens with this:
![image](https://user-images.githubusercontent.com/782127/90290661-45e90000-de4c-11ea-8201-3dbea8655023.png)

**Comment by ilyanaDev** [comment]
fixes #114

**Comment by ardalis** [comment]
You still need the ? confirm thing
