### ISSUE TITLE
Replace Moq with NSubstitute

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#1141]
See: 
https://ardalis.com/porting-moq-nsubstitute/

**Comment by sadukie** [comment]
See also: https://blog.nimblepros.com/blogs/moq-vs-nsubstitute-code-comparisons/

**Comment by radekwojpl2** [comment]
If this task is free I can do that.

**Comment by ardalis** [comment]
Go for it

**Comment by radekwojpl2** [comment]
Here is pull request https://github.com/DevBetterCom/DevBetterWeb/pull/1165.
I have notice that tests for DevBetterWeb.Vimeo.Tests are not working, should I do something with them ?

**Comment by ardalis** [comment]
@radekwojpl2 can you fix the tests/build and I'll pull in your PR?
