### ISSUE TITLE
Bug: Problem with account creation user experience

### ISSUE THREAD

**Issue by sadukie** [DevBetterCom/DevBetterWeb#1229]
Given that the user is a paying member and they get the email from the account
When they click the link and set up their account,
It shouldn't go to an error message.

It should probably redirect to https://devbetter.com/User/MyProfile

Thanks to @ETHammel for bringing this to my attention.

- He was able to log into the system with his username and password that he did submit.
- So **something** is failing in this process but it's not displaying a friendly error for the person signing up.

**Comment by SalZaki** [comment]
Happy to pick this up, if thats ok :)

**Comment by sadukie** [comment]
@SalZaki Let's check with @ShadyNagy to make sure this isn't related to something he's been fixing.

**Comment by ShadyNagy** [comment]
When I go to the confirmation link 
https://localhost:5011/Identity/Account/NewMemberRegister/ghghghgf/xvdsdfl@gmail.com

![image](https://github.com/DevBetterCom/DevBetterWeb/assets/6225593/24553161-294e-4d04-8074-ca3342b2509c)
