### ISSUE TITLE
Add Member Testimonial by James Purcell

### ISSUE THREAD

**Issue by jamescpurcell** [DevBetterCom/DevBetterWeb#131]
This is a feature to add a slot for my picture and testimonial for the DevBetter.com website.

**Comment by ardalis** [comment]
Hey @jamescpurcell is this still on your list to do?

**Comment by ardalis** [comment]
Closing this; you're welcome to reopen it if you're so inclined. Cheers and happy holidays!

**Comment by jamescpurcell** [comment]
Yeah sorry been real busy around here. I want to take the time to write a good review. Once I am ready I'll open an issue with a pr. 

Happy Holidays also hope the family is doing well!
