### ISSUE TITLE
Admin Page

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#162]
Main link to Admin in header nav should go to an Admin page with links to:

- Manage Users
- Manage Books
- Etc.

**Comment by ashleighchun** [comment]
Ill take this one

**Comment by justSteve** [comment]
I'd like to take this one on and would like clarification on what you have in mind. Currently the admin link shows 'Users'. Would you like a 2-tier link in the nav? Or a landing page at Admin with a list of links to Users, Books, etc?

**Comment by ardalis** [comment]
The latter. Just a simple /Admin/Index.cshtml with a bullet list of links to Manage Users, Manage Books. Move the current user admin functionality to another page and link to it.

**Comment by ardalis** [comment]
Don't spend too much time on it since there is another issue to update the back end UI with a nicer nav scheme.

**Comment by justSteve** [comment]
Initial updates completed at: https://github.com/justSteve/DevBetterWeb/tree/master/src/DevBetterWeb.Web

Would you like **ArchivedVideo** added? (is there any concept of an unarchived Video cuz if not it might make sense to drop  '_Archived_'.

Anything else falling under 'Etc.' at this point?

**Comment by ardalis** [comment]
Manage Videos would be fine as well, yes.

**Comment by ardalis** [comment]
Go ahead and make a Pull Request when you're ready

**Comment by ardalis** [comment]
Fixed by #169
