### ISSUE TITLE
Improved navigation for members-only admin-only site areas

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#163]
Implement something like SmartAdmin to organize and provide consistent navigation (in a responsive mobile-supported manner) for all of the non-public portions of the site.

https://wrapbootstrap.com/theme/smartadmin-asp.net-core-responsive-webapp-WB073L89G

Anyone have a preference for a particular theme or template to use? For now it should support ASP.NET Core but we could incorporate some features in Blazor and/or a JS framework as well just for learning purposes.

**Comment by ebrim** [comment]
Would something like this work? I used it on a previous project.

https://startbootstrap.com/theme/sb-admin-2

**Comment by ardalis** [comment]
Yep, something like that would work great. And it's nice that it's MIT licensed, unlike SmartAdmin.

**Comment by snowfrogdev** [comment]
Alright, I'm gonna take a crack at this one. @ardalis I'm guessing that your idea for a first pass at a UI revamp is to change the "shell" of the members-only part of the app, but keep the pages the same?

**Comment by ardalis** [comment]
Correct. Also you don't interact with it much but here's what the admin stuff looks like now:
![image](https://user-images.githubusercontent.com/782127/190511384-81b6e2f8-902f-4dc3-9864-cb28d13a315d.png)

Having that use a cleaner interface a la SmartAdmin or similar would be nice (or fitting it into an Admin section of such an interface, alongside member functionality).
