### ISSUE TITLE
Some 'getting started' questions

### ISSUE THREAD

**Issue by justSteve** [DevBetterCom/DevBetterWeb#168]
I've forked and built the project -- all green and I get the home screen. Given the fact I've gotten that far should mean the db was created and seeded, yes? But it's not showing up in SSMS's list of dbs. 

Looking at the efscripts.txt shows a set of commands to run but the first in the list: 
`dotnet ef migrations add DiscordUsername --context appdbcontext -p ../DevBetterWeb.Infrastructure/DevBetterWeb.Infrastructure.csproj -s DevBetterWeb.Web.csproj -o Data/Migrations`

yields: 
`The name 'DiscordUsername' is used by an existing migration.`

**Comment by ardalis** [comment]
You're almost there. The only EF scripts you need to run to get started locally are the two dotnet ef database update commands that need to run from specific folders mentioned. Then to seed the database open program.cs and uncomment the line near the top of the main method that calls Seed().

**Comment by justSteve** [comment]
Thanks. Before I unleash more questions perhaps I should ask if there's a link to a recording that overviews the app.

**Comment by ardalis** [comment]
I sent you a couple of questions on Discord. I don't have a recording currently but I was thinking one might be useful. If nothing else the Readme needs updated with better "Getting Started Locally" instructions.

**Comment by ardalis** [comment]
I think I've updated the README with what's needed. Can you confirm @justSteve ?

**Comment by matthiasjost** [comment]
I had no issues, no letting the project run! I also had issued the first time I tried.
