### ISSUE TITLE
Generate billing report

### ISSUE THREAD

**Issue by ilyanaDev** [DevBetterCom/DevBetterWeb#174]
Generate/format a report (for admins) listing:

- new signup - person and date
- renewals - person and date
- cancellations - person and date
- charges - person, date, fees paid

**Comment by ardalis** [comment]
Is this 1 report or 4? Are you thinking it will look something like this?

```
New Signup | John Doe | 5 Jan 2021
Renewal | Jane Doe | 6 Jan 2021
Cancellation | Joe Doe | 10 Jan 2021
```

Or will there be a New Signups report with names and dates, a Renewals report with names and dates, etc?

**Comment by ilyanaDev** [comment]
billing report: list charges and associated fees by date for given date range. Will add other reports in separate issue

**Comment by ilyanaDev** [comment]
Functionality achieved directly through stripe
