### ISSUE TITLE
Add an ILogger abstraction to Core and an adapter in Infrastructure

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#201]
We may want to log things in Core services/handlers/etc but we don't want a direct dependency on AspNetCore's ILogger.

Create our own ILogger that can easily be adapted to AspNetCore's logger as needed.

For reference, see:
https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/ApplicationCore/Interfaces/IAppLogger.cs
https://github.com/dotnet-architecture/eShopOnWeb/blob/master/src/Infrastructure/Logging/LoggerAdapter.cs

**Comment by rickhodder** [comment]
I'll take this one

**Comment by Rostech** [comment]
@ardalis looks like this is already implemented in #212.

**Comment by ardalis** [comment]
Thanks, closing.
