### ISSUE TITLE
Move JSON Parsing in Member to its own Service

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#202]
Move the JSON parsing code from the handler in Member to its own service.
Add unit tests and logging.
Make sure to only depend on System.Text.Json.

**Comment by mmutiso** [comment]
I could help with this

**Comment by ardalis** [comment]
Thanks, @mmutiso. Feel free to send a PR.

**Comment by Rostech** [comment]
Hey, @ardalis. I see that this issue is still 'open'. Can I take it?

**Comment by ardalis** [comment]
Sure, go for it. Thanks!

**Comment by Rostech** [comment]
@ardalis, I think I don't have permission to push/create a new branch.

**Comment by Rostech** [comment]
@ardalis, I'm not sure I have the needed permissions to push chahnged. Could you please check if this is the case? 
Thanks.

**Comment by ardalis** [comment]
@Rostech you can fork it first then make the changes in your fork and then PR from there, btw.

**Comment by Rostech** [comment]
Yeah, I missed the forking part. It's fine now, thanks.

**Comment by snowfrogdev** [comment]
@ardalis looks like this was done with #769, is anything missing?

**Comment by ardalis** [comment]
No looks good to close. Thanks!
