### ISSUE TITLE
Wrap Stripe in Adapter

### ISSUE THREAD

**Issue by ilyanaDev** [DevBetterCom/DevBetterWeb#205]
Goal is to remove all "using Stripe" statements from all files but the adapter objects, in order to clean up the codebase.

**Comment by ardalis** [comment]
Yes. Create abstractions that live in Core and are implemented in Infrastructure.
Web Controllers/Endpoints should have these abstractions injected and shouldn't know about their implementation details.

**Comment by ilyanaDev** [comment]
completed with PR #211
