### ISSUE TITLE
"Dereferencing of a possibly null reference" build errors under .Net Core Version Build 5.0.201

### ISSUE THREAD

**Issue by rickhodder** [DevBetterCom/DevBetterWeb#210]
It appears that .NET Core 5.0.201 has elevated the error CS8602 from a build warning to a build error 

Steps to reproduce:

1. If you dont have .NET Core 5.0.201 on your machine, install the SDK https://dotnet.microsoft.com/download/dotnet/5.0
2. Execute the following from the solution folder:

dotnet new globaljson --sdk-version 5.0.201

This will create a global.json that makes the build command build the solution in 5.0.201

3.  Execute the following from the solution folder

dotnet build

You will see something similar to the following:

C:\GitHub\DevBetterWeb\src\DevBetterWeb.Core\Entities\Member.cs(194,9): error CS8602: Dereference of a possibly null reference. [C:\GitHub\DevBetterWeb\src\DevBetterWeb.Core\DevBetterWeb.Core.csproj]
C:\GitHub\DevBetterWeb\src\DevBetterWeb.Core\Entities\Member.cs(205,9): error CS8602: Dereference of a possibly null reference. [C:\GitHub\DevBetterWeb\src\DevBetterWeb.Core\DevBetterWeb.Core.csproj]
    0 Warning(s)
    2 Error(s)

Build FAILED.

4. Modify the global.json file to use 5.0.100 (the .net version of the projects in the solution

5.  Execute the following from the solution folder

dotnet build

6. Build passes

**Comment by ShadyNagy** [comment]
@rickhodder 
Is that finished could we close it if yes?
