### ISSUE TITLE
Style Videos Page

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#27]
The list of past videos should be styled nicely and ideally should include embed links that you can just click on to start viewing each video (perhaps from the details screen - main screen probably should just be a compact list or table).

Show notes should probably only be displayed on the details page for each video.

**Comment by Joe-LaRue** [comment]
after some discussion, I think we have settled on the idea that the video list page will just have a link to the video detail page, where notes and questions will be visible.  the questions page will be it's own separate page, publicly accessible, with timestamp links that will challenge auth.  At this point, the video list.

At this point a lot of that is done, but we should keep this issue open until it has been reviewed and accepted.

**Comment by ShadyNagy** [comment]
Vimeo added and the videos list has style. PR #420
