### ISSUE TITLE
Command Handlers in Infrastructure layer

### ISSUE THREAD

**Issue by mehdihadeli** [DevBetterCom/DevBetterWeb#276]
Hi @ardalis,
I saw in your code base you put some event handlers in the infrastructure layer, in this case you put events as `port` in `core layer` and event handlers as `adapter` in `infrastructure layer`. In most of the scenario we put event handlers in the application layer. 
According to clean architecture and port and adapter is this a valid action?

**Comment by ardalis** [comment]
Hi @mehdihadeli,

I don't always have a separate, explicit application layer. Also, this project is being built as a collaboration and learning exercise both with community members and members of my devBetter.com coaching program, so take all of the design decisions here with a grain of salt.

That said, I don't see anything particularly wrong with handlers in various projects, but usually I tend to put them either in the domain/core project or in the UI. If they need infrastructure I'd put them in the core project and use interfaces for the infrastructure concerns, and if they need to communicate with the UI (e.g. a notification pop-up that uses SignalR) I'll put those in the UI layer for simplicity.

Can you point me to the specific handler in this project you're asking about?

**Comment by mehdihadeli** [comment]
Thanks, @ardalis, for your explanation,
For example [MemberAddressUpdatedHandler](https://github.com/DevBetterCom/DevBetterWeb/blob/main/src/DevBetterWeb.Infrastructure/Handlers/MemberAddressUpdatedHandler.cs) as an adapter is in Infrastructure layer and its event [MemberAddressUpdatedEvent](https://github.com/DevBetterCom/DevBetterWeb/blob/main/src/DevBetterWeb.Core/Events/MemberAddressUpdatedEvent.cs) as a port is in core layer.

**Comment by ardalis** [comment]
Yeah that could certainly be moved to Core since it doesn't use anything from Infrastructure.

**Comment by mehdihadeli** [comment]
@ardalis Yes, So it depends on we can move or handler to each of infra, core or UI based on our need.

**Comment by ardalis** [comment]
Indeed. Usually you won't need them in infra. I would probably move that one to Core.
