### ISSUE TITLE
Profile photo cannot be replaced

### ISSUE THREAD

**Issue by matthiasjost** [DevBetterCom/DevBetterWeb#304]
Profile photo cannot be replaced: It can be saved, but the profile photo remains the same.

**Comment by matthiasjost** [comment]
The new photo is now available. Maybe the issue was client sided?

**Comment by ardalis** [comment]
Hopefully it was a caching issue. I wonder if there's something we can do to make sure that's not a problem, but it seems this issue at least can be closed.
