### ISSUE TITLE
Add `MemberByEmailSpec` Or `MemberLookupService` class with `MemberByEmail`  method

### ISSUE THREAD

**Issue by ilyanaDev** [DevBetterCom/DevBetterWeb#311]
Is there no `MemberByEmailSpec`? If not, would it make sense to try and add one so you don't need the double lookup here to get a userId by email and then a member by userid?

_Originally posted by @ardalis in https://github.com/DevBetterCom/DevBetterWeb/pull/309#discussion_r640855733_

**Comment by ardalis** [comment]
Maybe we should break down and (also) store email on Member. It's not something that changes frequently and if someone does change it (on User) we can just be sure to change it on the associated Member at the same time.
