### ISSUE TITLE
Duplicate subscriptions from edit user

### ISSUE THREAD

**Issue by ilyanaDev** [DevBetterCom/DevBetterWeb#314]
to manage subscription under manage members under admin

**Comment by ardalis** [comment]
What does this mean? Can you add more context?

**Comment by ilyanaDev** [comment]
the thing we talked about earlier - copy paste or cut paste the subscription editing stuff from manage users to manage subscription (which right now only cancels subscriptions)

**Comment by ardalis** [comment]
Got it.

Move subscription management to the Manage Subscriptions section (and out of the EditUser page)

**Comment by ardalis** [comment]
I think we can leave this as-is. It's not causing problems.
