### ISSUE TITLE
Book Categories: Software Development and Personal/Career

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#336]
Add Book Categories.

The current set of books should be listed as Software Development.

A new category should be listed for Personal/Career.

The Leaderboard should list the most popular books based on category (so, 2 lists of books, not just 1 as there is now).

The member/alumni leaderboards should continue to use total books read (at least for now).

**Comment by ShadyNagy** [comment]
@ardalis 
I am not sure about the book category
We have 2 categories that are clear
Do you want to show the 2 tables one for category 1 and one for category 2 side by side?
or you want select from the select-box so you will choose the category from it and then you will see the books for that category only on the table
I think option 2 is better
But I need confirmation from you.

**Comment by ardalis** [comment]
I want something like this:

1) Remove the 2-column layout.

2) Display the following one by one vertically:

Alumni Readers Leaderboard
- Show alumni members sorted by total books read across all categories

Tech Book Readers Leaderboard
- Show non-alumni members sorted by total tech books read

Tech Book Reading List
- Show Tech Books as it appear now, sorted by how many have read each one

Personal/Career Book Readers Leaderboard
- As above but for this category

Personal/Career Reading List
- As above but for this category
