### ISSUE TITLE
Stripe animation hangs

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#405]
When payment is processing, the Stripe button animation freezes and never recovers. Payment typically goes through, but users don't know that and so may try again, resulting in duplicate charges and subscriptions.

![image](https://user-images.githubusercontent.com/782127/129404985-20b698bf-4639-47fe-9d7f-545941fd8d79.png)

**Comment by ShadyNagy** [comment]
@ardalis 
I am interested to do this.

**Comment by ardalis** [comment]
Go for it.

**Comment by ShadyNagy** [comment]
@ardalis 
Fix #425

**Comment by ardalis** [comment]
This may be fixed - haven't tested it yet.

**Comment by ardalis** [comment]
As of today this is still an issue...

**Comment by ShadyNagy** [comment]
@ardalis 
Is that still has a problem?

**Comment by ardalis** [comment]
It is still a problem.

**Comment by ShadyNagy** [comment]
I Will take a look on it again.

**Comment by ShadyNagy** [comment]
When clicking the Subscribe it calls 3 endpoints create-customer, payment_methods, and create-subscription. It will be better to do all three steps by one step only so it needs to call one endpoint only.

- [ ] Make one endpoint not a controller for creating a subscription.
- [ ] remove the old endpoints and controllers if empty.

**Comment by ShadyNagy** [comment]
I do not think it will happen again as the Stripe WebHook event has been used.
