### ISSUE TITLE
Handle Cancellation of Duplicate Subscriptions

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#406]
Because of #405, users may have more than one concurrent subscription in Stripe. Cancelling the duplicate subscriptions generates a call to the subscription cancellation webhook, which in turn results in that workflow kicking off (and the user being removed from the Member role, etc.).

We should have a way to cancel a subscription in Stripe without necessarily *really* canceling the member.

Perhaps we can perform a check to see if the Member's email has *any* active subscription in Stripe before we remove them?

**Comment by ShadyNagy** [comment]
@ardalis 
I am interested to do this.

**Comment by ShadyNagy** [comment]
@ardalis 
We finished this by fixing Stripe WebHook issue #405, so I think we also need to close this issue.

**Comment by ardalis** [comment]
Sure; if we get any more duplicates for some reason we'll open a new issue.
