### ISSUE TITLE
Prevent duplicate subscriptions and charges via Stripe

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#413]
See: https://stackoverflow.com/questions/26392819/stripe-making-multiple-customers-with-same-email-address

**Comment by ShadyNagy** [comment]
@ardalis 
I am interested to do this.

**Comment by ardalis** [comment]
See what you can do with this one.

**Comment by ShadyNagy** [comment]
Fix #425

**Comment by ShadyNagy** [comment]
@ardalis 
Is that working fine now or does it still has a problem?

**Comment by Coop56** [comment]
@ardalis Looks like there was a PR merged for this issue.  Can it be closed or has it still been a problem?

**Comment by ardalis** [comment]
Unfortunately our most recent new subscriber encountered this same issue, so it doesn't appear to be fixed. They got an endless spinner from the checkout screen and then tried again, resulting in 2 subscriptions in Stripe with duplicate charges. That code is pretty much all just Stripe so I'm not sure what we can do on our end to fix it but I'm guessing we're not the only ones to encounter this...

**Comment by ardalis** [comment]
The duplicates seem to stem from the stripe button spinner hanging. Probably you would need to go to the purchase workflow in an incognito browser to reproduce the behavior. You can use a test card (see: https://stripe.com/docs/testing) but you'll need to coordinate with me so I can enable test mode for the stripe account, I think.

**Comment by ShadyNagy** [comment]
This issue should be finished by this PR #911
