### ISSUE TITLE
Add UI to Share a Video with a Starttime

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#426]
Videos are working and you can jump to a timestamp using a URL like this one:
https://devbetter.com/Videos/Details/590205100/300

The last 300 is the number of seconds to jump into the video. This isn't documented or discoverable, though. We need to add some UI to share a link to the video, and in the UI there should be a checkbox with the current time which, if checked, will append the time in seconds to the URL to be shared (allowing someone to jump to that point in the timeline). See YouTube's UI for an example.

**Comment by rjsmith2** [comment]
@ShadyNagy @ardalis 
I have slight problem with the URL design.  
It would look better if we do this:
`https://devbetter.com/Videos/590205100?start=300` ?  

https://devbetter.com/Videos/Details/590205100/300 - what decision was made to make this happen? Why do we have the URL constructed this way?

**Comment by ardalis** [comment]
Agreed we could drop Details from the url but that's mostly a result of our Razor Page folder organization. I would separate that request from the start time one, which I also agree looks better as a query string (and that would be consistent with how YouTube works).

**Comment by ShadyNagy** [comment]
@rjsmith2 
I am also agreed.

It will be something like this on video details.
![unknown](https://user-images.githubusercontent.com/6225593/132401645-9d58ac9c-f666-4f9d-b5c9-ec8e09edc3a2.png)

**Comment by ShadyNagy** [comment]
Done by PR #516
