### ISSUE TITLE
Questions list should show topics discussed in actual videos

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#427]
This page: https://devbetter.com/Questions

Should basically just show all of the summaries from videos, most recent first, and should be public so that search engines and people considering joining the group can see what's been discussed here.

**Comment by ShadyNagy** [comment]
Related to  #28 #197 and the question is not related to the comment at all see #197 .

**Comment by ardalis** [comment]
I'm not sure what you're asking. I agree this has nothing to do with 197. There's still nothing at devbetter.com/questions.

**Comment by ShadyNagy** [comment]
Here is what has already been done so I think this issue we need to close it.

### As an admin, I can open sessions (edit, delete, and details)
![image](https://user-images.githubusercontent.com/6225593/189445330-7580eed5-b44b-4c1f-88cd-ff93bf4f9466.png)

### In the details, I can add questions/topics to the session also I can vote for question/topic
![image](https://user-images.githubusercontent.com/6225593/189445261-bd78a0c7-26f0-4eff-acdf-bfe27359ad14.png)

### Recent questions will show some of the last questions/topics for public
![image](https://user-images.githubusercontent.com/6225593/189445435-a37dc002-df25-4a10-94c0-2f117f41f3fb.png)

### As a user, I can open the session details only and vote for some questions/topics.
![image](https://user-images.githubusercontent.com/6225593/189445574-0ad8325a-c4b1-4ba9-886d-51502908bbbe.png)

**Comment by ardalis** [comment]
Ok I need to see how this works in action and maybe some documentation is in order but I'll close this for now.
