### ISSUE TITLE
Missing an ability to view recorded meetings in DevBetter.com and be able to mark it completed

### ISSUE THREAD

**Issue by rjsmith2** [DevBetterCom/DevBetterWeb#431]
Until recently, I did not know that we would need to download video to our computer to be able watch full duration of the video past one hour mark, because any videos on our Dropbox DevBetter website would alwayts abruptly cutoff past one hour mark.   Being able to watch video in DevBetter.com without having to log into Dropbox to download the full video to our pc would be great!

@Coop56  mentioned this in discord.  Do consider having a way for members to mark videos completed so they would know they have viewed the videos without having to replay the video again to figure out if they already watched it or not.  The list is pretty long and we could easily forget where we left off at so this feature would help improve our UX greatly.

**Comment by ShadyNagy** [comment]
Part one is done by using Vimeo 
Part two is done on issue #586
