### ISSUE TITLE
Add Integration Test for HomeController

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#438]
Fail the build if the HomeController can't load the home page. I just deployed a change that added `ILogger` and Autofac couldn't resolve it (should have been `ILogger<T>`). I was being lazy and counting on the build to catch any problems but it didn't. Hopefully an integration test will.

**Comment by YaseenYo** [comment]
Hey, @ardalis I want to contribute to this project. Please help me get started.

**Comment by ardalis** [comment]
Have you written an ASP.NET Core integration test before? That's what you need to do for this one.

See: https://docs.microsoft.com/en-us/aspnet/core/test/integration-tests?view=aspnetcore-5.0
