### ISSUE TITLE
Video Comments

### ISSUE THREAD

**Issue by ShadyNagy** [DevBetterCom/DevBetterWeb#528]
I think it will be cool if we add comments for every video so members can add comments and it will be support MD.

**Comment by ShadyNagy** [comment]
Fix #790

**Comment by ardalis** [comment]
This issue is referring to this page: https://devbetter.com/Questions

Non-Members can get to that page, but not to the /Videos page. So, the idea is that the questions would (somehow) be shown on the /Questions page.

**Comment by ShadyNagy** [comment]
I thought it is the same comment and the question will be the root comments :)
