### ISSUE TITLE
Add Discord Bot to Notify When New Videos Are Available

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#578]
Whenever a new video is added to /Videos, send a message to a webhook in Discord corresponding to the `#coachingsessions`  channel.

**Comment by ShadyNagy** [comment]
CoachingSessionsNotifications added on appsettings.

**Comment by ShadyNagy** [comment]
PR #641

**Comment by ShadyNagy** [comment]
Added and will activate after upload all old videos.
