### ISSUE TITLE
Videos: Watched By Whom

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#586]
I don't expect most users will watch 100% of every video, so to keep this feature simple, let's add:

1) If someone watches the last second of a video, detect that and mark it as watched.
2) Display whether a video has been watched or not on the video details page. Add a link to "Mark as Watched" or "Mark as Unwatched" as appropriate to toggle status.
3) Add a visual cue to the main video list to indicate watched/unwatched videos (grey out watched videos or mark them with an icon or something)
4) Add an option to filter videos to only show watched or unwatched or both.

**Comment by ardalis** [comment]
Have three states:
- Unwatched (mark as watched)
- In Progress (just store videoId, userId, secondWatched) (mark as watched / unwatched)
- Watched (Mark as Unwatched)

Automatically mark as watched when video is completed (just like a podcast app would) by default.

- Profile Option
  - Mark videos as watched when last second is watched [ checkbox ]

YouTube just shows you where you last were in the video (a progress bar).

**Comment by ardalis** [comment]
All we really need is:

- nullable int LastSecondWatched.

if LastSecondWatched is null -> Unwatched
 1 - length-1 -> In Progress
 length -> Watched

**Comment by ShadyNagy** [comment]
Some parts are done on PR #791 but it needs one more PR after merging all pending PRs without the profile settings part as you suggest.
