### ISSUE TITLE
Remove ShowNotes from ArchiveVideo Entity

### ISSUE THREAD

**Issue by KyleMcMaster** [DevBetterCom/DevBetterWeb#603]
After reviewing the video search functionality, it was determined the `ShowNotes` property on the entity `ArchiveVideo` is no longer needed as the data that used to be present in this field now belongs in the `Description` property. `ShowNotes` can be removed the `ArchiveVideo` entity and any existing references to it can be updated to use the `Description` field.

**Comment by ShadyNagy** [comment]
Fix #795
