### ISSUE TITLE
Decouple Thumbnail Generation from Uploader

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#628]
This has been like this for 3 hours:
![image](https://user-images.githubusercontent.com/782127/150607772-8c0353ca-0c35-4914-8b75-3c4c93f1dde5.png)

There's no reason why, if the video is uploaded, the uploader still needs to be involved. It should just tell the devBetter API that the video has been uploaded (with video link etc) and be done. If thumbnails need made, another process can pick up an event or periodically run a query to see which videos lack thumbnails, and generate them.

**Comment by ardalis** [comment]
what do you think @ShadyNagy ?

**Comment by ShadyNagy** [comment]
now it is on another uploader command to change the Thumbnail
```powershell
.\DevBetterWeb.UploaderApp.exe -u -i [VimeoVideoId] -t [VimeoToken] -l https://devbetter.com/ -k [DevBetterApiKey] -v debug
```
PR #632

**Comment by ShadyNagy** [comment]
Delete video added in the uploader
```powershell
.\DevBetterWeb.UploaderApp.exe -d -i [VimeoVideoId] -t [VimeoToken] -l https://devbetter.com/ -k [DevBetterApiKey] -v debug
```

**Comment by ardalis** [comment]
From where? In one of the scheduled jobs already running in the website?

`    services.AddHostedService<DailyCheckService>();` ?

**Comment by ShadyNagy** [comment]
@ardalis 
So I need to put it inside this function `DailyCheckInitiatedEventHandler`

**Comment by ardalis** [comment]
yeah, probably easier than adding hangfire to the mix

**Comment by ShadyNagy** [comment]
done on PR #640
