### ISSUE TITLE
My Profile page suggestions

### ISSUE THREAD

**Issue by rjsmith2** [DevBetterCom/DevBetterWeb#696]
Some of the input fields are rather cryptic about what kind of input we should be putting in. For example, for CodingGame field, how I am supposed to know what it expects to receive? 
![image](https://user-images.githubusercontent.com/7023709/159269135-8cf3e45b-a6f4-4fd1-bf31-d4670aa35774.png)

My suggestion is to implement secondary labels to some fields, or perhaps, a pop-over "?" element that pops up a new tiny help window that informs user what to do with its input field.  Providing some help text like, for example, CodinGame should show something like "Example: `https://www.codingame.com/profile/<your profile id here>` where your profile id can be found by visiting this url: https://www.codingame.com/profile"

**Comment by ShadyNagy** [comment]
Fix #796
