### ISSUE TITLE
'What do others think?' people pictures ratio

### ISSUE THREAD

**Issue by Stratis-Dermanoutsos** [DevBetterCom/DevBetterWeb#782]
The picture of `Phil V.` is not a perfect rounded circle.

I checked the code and the component's classes are the same as the others. (file [`src/DevBetterWeb.Web/Views/Home/Index.cshtml`](https://github.com/DevBetterCom/DevBetterWeb/blob/main/src/DevBetterWeb.Web/Views/Home/Index.cshtml))

I checked the image file in [`images/people/philippe-vaillancourt.jpg`](https://github.com/DevBetterCom/DevBetterWeb/blob/main/src/DevBetterWeb.Web/wwwroot/images/people/philippe-vaillancourt.jpg) and it turns out that the dimensions are not squared.

So, I believe the issue can be fixed by cropping the image or applying a CSS property on all people's images to force a 1:1 ratio. I could send a PR myself if you wish.
It's only a visual issue anyway.

## Preview of the issue

![image](https://user-images.githubusercontent.com/38103639/176850393-b988cabb-6e7f-4e37-88c3-41971f09daba.png)

**Comment by ardalis** [comment]
@snowfrogdev thoughts?
