### ISSUE TITLE
Show Recent/Inactive Members

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#785]
Currently admins can view members in the same was as any other member, but once someone cancels their subscription and they are removed from the Members role, they no longer appear. It would be good for admins to be able to view non-current members in order to easily locate their information like GitHub username, email address, etc.

A checkbox on the members tab that only Admins would see could allow for this functionality. Something like:

[ ] Show Previous Members (no longer in Members role)

**Comment by ShadyNagy** [comment]
Fix #797

**Comment by ShadyNagy** [comment]
Fix #798
