### ISSUE TITLE
"Read by" total wrong for "Code that fits in your Head"

### ISSUE THREAD

**Issue by snowfrogdev** [DevBetterCom/DevBetterWeb#856]
The book shows up in my profile as a book I have read yet the total read associated to that book in the global leaderboard is 0.
![image](https://user-images.githubusercontent.com/22530235/184034056-efa2791a-7849-42ce-9712-802964da3387.png)
![image](https://user-images.githubusercontent.com/22530235/184034386-80cadebe-24c7-4932-aef4-15235e7eca34.png)

**Comment by ShadyNagy** [comment]
Thanks, @snowfrogdev this merge will fix this bug.
