### ISSUE TITLE
Subscription DropDownList is Empty in Edit User Page

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#858]
See screenshot:
![image](https://user-images.githubusercontent.com/782127/184216454-89e82fe2-ec58-4e50-b568-2241132415ec.png)

List should include options from MemberSubscriptionPlan. This is making it difficult to add a subscription to a new member.

**Comment by ShadyNagy** [comment]
@ardalis 
I just checked it and it is working but I need to add a SubscriptionPlan 1st from this page `/Admin/SubscriptionPlans`

**Comment by ShadyNagy** [comment]
Logger added on #859
