### ISSUE TITLE
Member Map without User/Member

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#879]
It should be possible to view the map of members without having to specify a member/user id.

This works
https://devbetter.com/user/map/60b5123e-5392-4b9a-b3bc-fd4a215d4252

This doesn't
https://devbetter.com/user/map

Probably a new URL of 
https://devbetter.com/map
or
https://devbetter.com/membermap

would make sense, too.

**Comment by ShadyNagy** [comment]
@ardalis 
The user id here is used to animate the user with this id.
Do you want to remove this option/animation totally?

**Comment by ShadyNagy** [comment]
I think I understood what you want. you want to keep this as it is so if the member click on another member map it will show.
and a new page for map creation to see the full map without animation related to issue #878

**Comment by ardalis** [comment]
Correct - I want a map that shows all members and isn't tied to any one of them. Thanks!
