### ISSUE TITLE
Add Links/Details to Admin Email Reminder for Cancelations

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#889]
Currently we get an email when someone cancels their devBetter subscription, like this:

![image](https://user-images.githubusercontent.com/782127/187728413-e3d8c660-e8b8-4a8c-b084-e9363aca714a.png)

It would be nice if this included the person's github alias, discord username, and stackoverflow email (if we know it) etc so that performing the actions can be done with the information available in the email.

**Comment by ShadyNagy** [comment]
I want to take this.
