### ISSUE TITLE
Crash when adding a new book as an alumni

### ISSUE THREAD

**Issue by snowfrogdev** [DevBetterCom/DevBetterWeb#897]
I tried adding a book and added a long multi-paragraph text to the description field and that led to an error. When I tried again but without any description at all, it worked. 

![image](https://user-images.githubusercontent.com/22530235/188638916-159f6333-8140-464b-8777-d02b1f7c62a3.png)

**Comment by ardalis** [comment]
Same behavior from the book admin page. There's apparently no validation occurring for length of text (at least for description).
