### ISSUE TITLE
As an alumni, when adding a new book, I want to be able to choose the book's category

### ISSUE THREAD

**Issue by snowfrogdev** [DevBetterCom/DevBetterWeb#898]
Since we now have two book categories, when adding a new book as an alumni, we should be able to say in which of the two categories it falls.
![image](https://user-images.githubusercontent.com/22530235/188640474-86b4fdb1-dbe0-4ca8-bcf5-e3bdade44ae5.png)

The book should then appear in the correct list in the leaderboard section.

**Comment by snowfrogdev** [comment]
Just noticed this:
![image](https://user-images.githubusercontent.com/22530235/189124439-4f1afa44-6dcc-4aef-8cc4-61cdde50687b.png)

So it looks like the functionality is already there. Maybe I just missed it. Can anyone confirm that this works as intended in prod, I've already added a book and can't add another one.

**Comment by ShadyNagy** [comment]
Yes, alumni members can add one book only. This feature has already been deployed.
