### ISSUE TITLE
Member Birthday Visibility

### ISSUE THREAD

**Issue by ardalis** [DevBetterCom/DevBetterWeb#910]
- Make Member birthday, if set, appear on their profile
- Add more info on the edit profile page that indicates that, if set, birthday will be visible to other devBetter members and may be used to celebrate their day via Discord, coaching sessions, etc.
- Ensure the edit profile page includes a means by which to remove one's birthday

**Comment by snowfrogdev** [comment]
> * Ensure the edit profile page includes a means by which to remove one's birthday

This is already possible by simply making the birthdate day and month fields empty and saving. Would you like me to make a little garbage icon instead to make it more obvious and user-friendly?

**Comment by ardalis** [comment]
If it already works and is obvious enough then consider that requirement met.
