### ISSUE TITLE
Add "Member Resources" link to home page navbar

### ISSUE THREAD

**Issue by snowfrogdev** [DevBetterCom/DevBetterWeb#940]
### Context
At the moment, when a member is logged-in and they visit the devbetter.com homepage, there is no easy way to navigate to the member-only section of the app. They have to click the little person icon dropdown and then on "My Profile".

### Requirements
- Add a "Member Resources" link to the home page navbar
- The link should be visible to logged in members only (alternatively it could be visible to all and redirect non-logged-in users to the login page).
- The link should navigate to https://devbetter.com/Resources

**Comment by ShadyNagy** [comment]
@snowfrogdev 
Regarding the feature you've requested in the issue, I have noticed that it appears to be already implemented in the application. Could you please confirm if this is the case, or if there are additional aspects or enhancements related to it that you'd like to see?

**Comment by snowfrogdev** [comment]
Yeah. We've redesigned the navbar since then.
